package com.econotravel.api.repositories;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import java.util.List;

@Component
public class SampleDataLoader {


    private ExperienceRepository experienceRepository;

    @Autowired
    public SampleDataLoader(ExperienceRepository experienceRepository) {this.experienceRepository = experienceRepository; }

    @PostConstruct
    public void loadSampleData() {
        experienceRepository.saveAll(List.of(

        new Experience(1L,"https://media.revistagq.com/photos/603f9b08ea88c7db6f596dd7/16:9/w_2560%2Cc_limit/dick-honing-XCLGjBwKvSw-unsplash%2520(1).jpg", "Paseo en bicicleta por el Montseny", "Disfruta de un hermoso paseo en bicicleta por el increíble Parque Natural del Montseny. Una escapada veraniega perfecta para parejas, familias y amigos que nos permitirá conocer nuevos y sorprendentes lugares. El recorrido que os proponemos comienza con una larga subida con algunos descansos, combinando asfalto y pistas anchas, culminando en un mirador con magníficas vistas del Vallés y el mar. Desde aquí continuaremos la bajada combinando senderos, pistas y algún tramo de carretera y terreno mixto para visitar la zona de Santa Fe, donde descubriremos la Ermita y el Bosque de las Secuoyas. Para finalizar, acudiremos al restaurante María Rosa de Palautordera, donde disfrutaremos de una excelente comida casera con butifarra blanca y negra y munxetes del Montseny.", 250.00, "5h", true, "Actividad disponible para todas las edades. Disponemos de bicicletas accesibles para personas con movilidad reducida en el tren inferior así como sillines con capacidad para niños menores de 5 años (peso máximo 20kg)." ),
        new Experience(2L, "https://c.pxhere.com/photos/2a/51/ship_boat_vessel_dock_mooring_mast_bow_stern-420002.jpg!s1", "Descubre la costa en barco de vela", "Disfruta de un hermoso paseo acuático en barco de vela por la increíble costa de Barcelona. Una escapada veraniega apta incluso para los días más calurosos del año. Descubre los encantadores alrededores de la ciudad de Barcelona y visita desde el mar sus más impresionantes playas y calas. Comenzaremos la excursión en el Puerto de Barcelona, desde donde partiremos hacia el norte para visitar playas como la Mar Bella, la Playa de la Mora y la Playa de los Pescadores. A bordo de la embarcación podremos disfrutar de una selección de quesos y embutidos catalanes acompañada de cava brut y zumos de frutas. Asimismo, pararemos cerca de la Playa de Montgat para realizar una actividad de buceo de superficie que nos permitirá apreciar la diversidad de la fauna marítima local y su ecosistema. Finalizaremos la excursión en el mismo puerto del que partimos", 280.00, "4h", true, "Actividad disponible para todas las edades. Pasarela para silla de ruedas disponible bajo reserva."),
        new Experience(3L, "https://bcityng.com/wp-content/uploads/elementor/thumbs/raimond-klavins-18iU7bHCjeo-unsplash-2-scaled-e1627383735291-paqaw04px7s3cn0u8l2a9omu019e6i6vwg018n01iw.jpg","Descubre la Barcelona modernista de noche", "Desplazarse a pie es una de las mejores formas de descubrir las maravillas modernistas que se esconden en el barcelonés distrito del Eixample, ubicado en el centro de la ciudad. En esta excursión de cuatro horas, descubriremos los principales emblemas del modernismo y visitaremos los templos y edificios más célebres del arquitecto Gaudí. El tour incluye visita guiada al interior de la Casa Batlló y la Sagrada Familia, así como parada para cenar en el restaurante típico catalán Can Masiá, donde disfrutaremos de las mejores carnes de la región acompañadas de vinos de las tierras del Baix Empordá. El restaurante también ofrece opciones vegetarianas y veganas así como menú para niños. Cava aparte.", 200.00, "4h", true, "Actividad disponible para todas las edades. Accesibilidad garantizada para sillas de ruedas."),
        new Experience(4L, "https://blog.schoolspecialty.com/wp-content/uploads/2018/07/Gardening-Active-Play-Ideas-for-Summer.jpg", "Del huerto a la mesa", "Comparte con los más pequeños las maravillas de la naturaleza. En esta excursión breve de tres horas, podréis plantar vuestras propias hortalizas y verduras en el huerto de Can Gilabert, ubicado en el corazón del Montbaig. Durante una hora y media, aprenderéis a cuidar de vuestro propio huerto, plantaréis y abonaréis vuestras propias plantas, y también recogeréis parte de los ingredientes que los expertos chefs de Can Gilabert utilizarán para preparar la posterior cena, donde disfrutaréis de la experiencia de consumir productos recién recogidos de la tierra con vuestras propias manos. Actividad ideal para familiarizar a los más pequeños de la familia con el estilo de vida rural y la agricultura sostenible. Asimismo, obtendréis como obsequio una botella de aceite virgen extra cultivado y preparado en Can Gilabert, obra de la familia Gilabert, que lleva más de 80 años cultivando olivos.", 145.00, "3h", true, "Actividad disponible para todas las edades. El acceso al huerto en silla de ruedas está garantizado." ),
        new Experience(5L, "https://cdn2.civitatis.com/portugal/portimao/galeria/header/entrando-kayak.jpg", "Excursión en Kayak", "La Costa Brava es un paraje privilegiado tanto por sus paisajes como por su fondo marino, un tesoro marítimo y terrestre que impresiona a todo aquél que lo visita. Admira los encantos ocultos de esta zona con la ruta en kayak y snorkel de Nauticfun Costa Brava. Empezarás navegando en kayak por este maravilloso entorno para terminar con el snorkel descubriendo sus fondos marinos. ¿Quieres descubrir unos de los rincones más bonitos de la Costa Brava? ¿Entrar en cuevas oscuras y profundas donde sólo se puede acceder en kayak? Realiza una excursión con uno de los guías de Nauticfun Costa Brava y descubre la belleza de este litoral. La navegación en kayak es una actividad sencilla que te acercará a los rincones más bellos y desconocidos. Tras el paseo en kayak prepárate para disfrutar de una de las actividades más relajantes y espectaculares que se puede experimentar, el snorkel. Te sumergirás en cristalinas aguas y disfrutarás de un placentero baño.", 85.50, "6h", true,"Actividad disponible solo para mayores de 16 años y nadadores experimentados. No es recomendable claustrofóbicos."),
         new Experience(6L, "https://www.piedradetoque.es/wp-content/uploads/parapente_dos.jpeg", "Explorando los cielos", "Ideal como toma de contacto para los menos aventureros. Consiste en un vuelo de descenso, de aproximadamente 10-15 minutos de duración, este tiempo dependerá de las condiciones meteorológicas del día reservado. La experiencia completa tiene una duración de 1 hora. El deporte del parapente es la forma más sencilla y emocionante de volar y también el aparato volador más ligero que existe: un equipo de vuelo completo ronda los 20 kg., y se despega y aterriza con los pies. Se utiliza un planeador dirigible, semirígido y muy ligero que se maneja fácilmente. Este planeador es simple: el aire entra por la parte delantera e infla el interior de las dos telas, superior e inferior. La tela del planeador actúa igual que el ala de un avión, empujando hacia arriba y permitiendo mantener el vuelo. El parapente va unido mediante finas cuerdas de material altamente resistente a un arnés en el que el piloto va sentado disponiendo de un mando en cada mano que, al accionar la parte trasera de cada semi-ala, le permite variar la trayectoria de vuelo.", 220.00, "15min", true, "Actividad disponible solo para mayores de 18 años y peso máximo de 95Kg.")

        ));
    }

}